// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_name_to_migrationtype_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_name_to_migrationtype_class));
        
        string IMigrationMetadata.Id
        {
            get { return "201810071733315_adding_name_to_migrationtype_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
